### PR TITLE
fix wrong $headers initial value

### PR DESCRIPTION
**Pull request by luizbills**

### CODE REVIEW

**Comment by timiwahalahti** [comment]
First time reported here #129, fixed in PR #146 and merged in 8bccce6.

We should discuss if we wan't to change the default behavior from string to array. One thing to consider here is possible breakage if someone is already using `$headers` as a string.

**Comment by luizbills** [comment]
But is more intuitive use it as an array. Internally it is used as array
https://github.com/libreform/wp-libre-form/blob/7fa947b432fceae26c87c1cb6cfc7c20332db6f5/inc/wplf-form-actions.php#L53

Nobody likes annoying warnings

**Comment by timiwahalahti** [comment]
I totally agree with you. IMO we should use an array.

I'm just a bit worried, that someone might be using `$headers` as a string and changing the default to the array would break something on someone's production. For example is the hook is used and `$headers` altered like `$headers .= ' From: example@examp.le'`.

**Comment by timiwahalahti** [comment]
I think we should merge this, as the next version will introduce other breaking changes as well. @k1sul1 thoughts?

**Comment by luizbills** [comment]
Yes, merge please. `[]` in strings causes fatal error in PHP 7.2 (I don't know in old versions).

https://glot.io/snippets/f99tzm0i7t

**Pull request merged**
