### PR TITLE
Optional media files

### PR DESCRIPTION
**Pull request by hencca**
Per form choice whether file input uploads wind up in media library.

### CODE REVIEW

**Comment by hencca** [comment]
- Checkbox selected by default. 
- No behavior change will occur when updating plugin. 

User will notice a new meta box with checkbox asking whether file inputs will be added to media library. The checkbox will be selected by default, so that there is no change in plugins behavior when updating plugin.

**Comment by k1sul1** [comment]
Good news:
this works.

Bad news: 
you've reindented the files, essentially making them unreadable.

**Comment by k1sul1** [comment]
Ok it seems that the diffs got ruined in dfcfd4a. Let's see if I can rebase my way out of this.

**Comment by k1sul1** [comment]
Yes.

**Pull request merged**
